name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Group rg-githucactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: North Central US
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy Storage account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGropName: rg-githubactions
          subscriptions: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storage.account.json
          deploymentMode: Incremental
