name: armTemplateDeployment

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  ArmDeploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions with AZ CLI
        uses: Azure/cli@v1
        with:
          inlinescript: |
            az deployment sub create --location "North Central US" --template-file  ./arm-templates/resoucegroup.json


